"""Sentence templates for synthetic customer-support messages (Bahasa Indonesia).

Slots
-----
Entity slots (labelled):   {PER} {PER2} {ADDR} {ADDR2}
Regex-PII slots (label O): {NIK} {EMAIL} {PHONE}   -> raw value OR a [REDACT_*] placeholder,
                                                    because in the pipeline the regex layer runs
                                                    *before* NER (data minimisation).
Context slots (label O):   {HON} {CITY} {PROD} {PRODNAME} {BRAND} {APP} {PAY} {TICKET}
                           {CUSTNO} {AMOUNT} {MONTH} {YEAR} {AGE} {DATA}

TRAIN_TEMPLATES and DEV_TEMPLATES are disjoint on purpose: the dev split measures
generalisation to *unseen phrasings*, not memorisation of templates.
"""

TRAIN_TEMPLATES: dict[str, list[str]] = {
    "person": [
        "Nama saya {PER}.",
        "Halo, saya {PER}.",
        "Perkenalkan, nama saya {PER}, pelanggan {BRAND} sejak {YEAR}.",
        "Selamat pagi, saya {PER}, ingin menanyakan tagihan bulan ini.",
        "Saya {PER}, mau komplain soal internet yang lemot.",
        "Ini dengan {HON} {PER}, saya mau tanya status pengaduan.",
        "min, aku {PER}, kuotaku kok cepet habis ya",
        "halo kak, {PER} di sini",
        "Nama lengkap saya {PER}, nomor pelanggan {CUSTNO}.",
        "Saya atas nama {PER} ingin berhenti berlangganan.",
        "Akun ini terdaftar atas nama {PER}.",
        "Nama pemilik kartu adalah {PER}.",
        "Tagihan atas nama {PER} belum bisa dibayar lewat aplikasi.",
        "tolong cek tagihan a.n. {PER} ya",
        "Pembayaran a/n {PER} sudah saya transfer kemarin.",
        "Rekening pengirim atas nama {PER}.",
        "Mohon diproses, pemohon {PER}.",
        "Saya {PER}, {AGE} tahun, ingin daftar paket baru.",
        "Salam, {PER}",
        "Terima kasih, {PER}.",
        "Hormat saya,\n{PER}",
        "{PER} di sini, mau tanya promo {PROD}.",
        "{PER}. Nomor pelanggan {CUSTNO}.",
        "Saya bernama {PER} dan ingin mengajukan keluhan.",
        "Panggil saja saya {PER}.",
        "Yang bicara {HON} {PER}.",
        "Nama saya {PER}, tapi akunnya pakai nama {PER2}.",
        "Teknisi yang datang bernama {PER}.",
        "Kurir {PER} bilang paketnya sudah diantar, padahal belum.",
        "Tadi saya ditelepon oleh petugas bernama {PER}.",
        "Tolong sampaikan terima kasih ke {HON} {PER} yang sudah membantu.",
        "Suami saya, {PER}, yang biasanya bayar tagihan.",
        "Istri saya {PER} mau ditambahkan sebagai pengguna.",
        "Anak saya {PER} yang pakai nomor ini.",
        "Nomor ini milik ibu saya, {HON} {PER}.",
        "Kartu ini atas nama almarhum ayah saya, {PER}.",
        "Saya mewakili {HON} {PER} untuk pengurusan balik nama.",
        "Mohon balik nama dari {PER} ke {PER2}.",
        "Pelanggan atas nama {PER} minta dihubungi kembali.",
        "CS sebelumnya, {HON} {PER}, sudah mencatat keluhan saya.",
        "Saya sudah bicara dengan {PER} dari tim teknis.",
        "{PER} dan {PER2} sama-sama pakai paket keluarga.",
        "Penerimanya {PER}, bukan saya.",
        "Tolong titipkan ke tetangga saya, {HON} {PER}.",
        "mas {PER} yg kmrn pasang modem ga balik2",
        "kata teknisinya, {HON} {PER}, kabelnya putus",
        "Saya {PER}, sudah tiga kali telepon tapi belum ada solusi.",
        "Assalamualaikum, saya {PER} dari tim keuangan kantor.",
        "Tolong kabari {HON} {PER} kalau teknisi sudah berangkat.",
        "Adik saya {PER} lupa PIN kartunya.",
        "Yang memesan kemarin {PER}, saya hanya menanyakan statusnya.",
        "nama sy {PER}, mau aktivasi kartu baru",
        "aku {PER} kak, mau nanya paket {PROD}",
        "Tolong ubah nama pemilik akun menjadi {PER}.",
        "Pengaduan saya dibuat oleh {HON} {PER} minggu lalu.",
        "Atas nama siapa? Atas nama {PER}.",
        "Saya {PER} dan {PER2}, kami mau pasang di dua rumah.",
        "Nama di KTP saya {PER}.",
        "bang {PER} td bilang besok diperbaiki",
        "{HON} {PER}, pelanggan pascabayar, minta tagihan dikirim ulang.",
        "Mertua saya, {HON} {PER}, belum paham cara pakai aplikasinya.",
        "Tanda tangan penerima: {PER}",
        "Mohon konfirmasi pembayaran dari {PER}.",
        "Selamat malam kak, saya {PER}. Mau tanya kenapa internet putus-putus.",
        "Untuk verifikasi, nama ibu kandung saya {PER}.",
    ],
    "address": [
        "Saya tinggal di {ADDR}.",
        "Alamat saya {ADDR}.",
        "Alamat pemasangan: {ADDR}",
        "Mohon kirim modem ke {ADDR}.",
        "Internet di {ADDR} mati total sejak pagi.",
        "Tolong pindahkan layanan saya ke {ADDR}.",
        "Saya baru pindah ke {ADDR}, bagaimana cara pindah alamat?",
        "Apakah {ADDR} sudah terjangkau jaringan fiber?",
        "Teknisi bisa datang ke {ADDR} besok pagi?",
        "Paket dikirim ke {ADDR} tapi belum sampai.",
        "Kurir bilang {ADDR} tidak ditemukan.",
        "Rumah saya di {ADDR}, dekat masjid.",
        "Lokasi gangguan di {ADDR}.",
        "kirim ke {ADDR} ya kak",
        "almt sy {ADDR}",
        "sinyal di {ADDR} jelek bgt",
        "Alamat penagihan diubah menjadi {ADDR}.",
        "Alamat lama {ADDR}, alamat baru {ADDR2}.",
        "Saya pindah dari {ADDR} ke {ADDR2}.",
        "Domisili saya sekarang di {ADDR}.",
        "Kantor kami di {ADDR} butuh pemasangan dedicated line.",
        "Pasang baru di {ADDR} bisa kapan?",
        "Survei lokasi ke {ADDR} jadi hari ini?",
        "tolong cek jaringan di {ADDR}",
        "Alamat: {ADDR}",
        "Dikirim ke alamat {ADDR} saja.",
        "Tagihan fisik dikirim ke {ADDR}.",
        "Gangguan di {ADDR} sudah dari semalam.",
        "Saya di {ADDR}, sudah tiga hari tidak bisa internet.",
        "Titik pemasangan di {ADDR}, lantai 2.",
        "Modem rusak, tolong ambil di {ADDR}.",
        "rumahku di {ADDR}, kapan teknisi dtg?",
        "Toko saya di {ADDR} mau pasang internet bisnis.",
        "Tiang di depan {ADDR} roboh, kabelnya putus.",
        "Mohon teknisi ke {ADDR} setelah jam 4 sore.",
        "Alamat pengiriman kartu SIM: {ADDR}",
        "Apakah bisa COD ke {ADDR}?",
        "Sekarang saya kos di {ADDR}.",
        "tolong ganti alamat jd {ADDR}",
        "ODP di dekat {ADDR} penuh katanya.",
        "Saya mau lapor, di {ADDR} ada kabel menjuntai.",
        "Pengiriman ke {ADDR} kena ongkir berapa?",
        "Kontrakan saya di {ADDR}, pemiliknya sudah setuju dipasang.",
        "Lokasi: {ADDR}",
        "Balik nama sekalian pindah ke {ADDR}.",
    ],
    "both": [
        "Nama saya {PER} dan tinggal di {ADDR}.",
        "Saya {PER} dari {ADDR}.",
        "Saya {PER}, alamat {ADDR}, mau lapor gangguan.",
        "Atas nama {PER}, alamat pemasangan {ADDR}.",
        "Kirim ke {PER}, {ADDR}.",
        "Penerima: {PER}, {ADDR}",
        "Paket untuk {HON} {PER} di {ADDR}.",
        "halo min sy {PER}, rumah di {ADDR}, wifi mati dr pagi",
        "saya {PER} tinggal di {ADDR}",
        "Ibu saya {PER} tinggal di {ADDR}, beliau mau pasang internet.",
        "Teknisi {PER} belum datang ke {ADDR}.",
        "Tolong antar ke {ADDR}, penerima {HON} {PER}.",
        "Saya {PER}, pelanggan di {ADDR}, ingin upgrade ke {PROD}.",
        "Dengan hormat, saya {PER} yang beralamat di {ADDR} mengajukan keluhan.",
        "{PER}, {ADDR}",
        "Mohon kirim ulang tagihan ke {PER}, {ADDR}.",
        "Selamat siang, saya {PER}. Internet di {ADDR} sering putus.",
        "Paket atas nama {PER} harusnya ke {ADDR}, bukan ke alamat lama.",
        "Saya {PER}, mau pindah layanan dari {ADDR} ke {ADDR2}.",
        "{HON} {PER} di {ADDR} sudah menunggu teknisi dari pagi.",
        "Nama saya {PER}, sekarang domisili di {ADDR}.",
        "Tolong dicatat: {PER}, alamat {ADDR}, minta dijadwalkan survei.",
        "Rumah {HON} {PER} di {ADDR} belum ada sinyal.",
        "sy {PER}, almt {ADDR}, tlg dicek ya",
        "Pemilik rumah {PER}, alamat {ADDR}, sudah setuju pemasangan tiang.",
        "Kami, {PER} dan {PER2}, tinggal di {ADDR}.",
        "Kurir {PER} tidak menemukan {ADDR}.",
        "{PER} - {ADDR}",
        "Anak saya {PER} kos di {ADDR}, mau pasang wifi.",
        "Saya {PER}. Alamat pemasangan baru: {ADDR}. Mohon dijadwalkan.",
        "Tolong kirimkan kartu pengganti untuk {PER} ke {ADDR}.",
        "saya {PER} warga {ADDR}, di sini banyak yang gangguan",
        "Invoice atas nama {PER} dikirim ke {ADDR} ya.",
    ],
    "form": [
        "Nama: {PER}\nAlamat: {ADDR}",
        "Nama: {PER}\nAlamat: {ADDR}\nNo. HP: {PHONE}",
        "Nama lengkap: {PER}\nNIK: {NIK}\nAlamat: {ADDR}\nEmail: {EMAIL}",
        "Nama : {PER}\nNo KTP : {NIK}\nAlamat : {ADDR}",
        "Data pemasangan -> Nama: {PER}, Alamat: {ADDR}, Telp: {PHONE}",
        "NAMA: {PER}\nALAMAT: {ADDR}\nHP: {PHONE}",
        "Nama pelanggan: {PER}\nNo. pelanggan: {CUSTNO}\nAlamat: {ADDR}",
        "Penerima: {PER}\nAlamat lengkap: {ADDR}\nTelepon: {PHONE}",
        "nama: {PER}\nalamat: {ADDR}",
        "Nama: {PER} | Alamat: {ADDR} | HP: {PHONE}",
        "1. Nama: {PER}\n2. Alamat: {ADDR}\n3. Email: {EMAIL}",
        "Pemohon: {PER}\nLokasi: {ADDR}\nPaket: {PROD}",
        "Nama/Alamat: {PER} / {ADDR}",
        "Nama sesuai KTP: {PER}\nAlamat sesuai KTP: {ADDR}\nAlamat domisili: {ADDR2}",
    ],
    "regex": [
        "Nomor HP saya {PHONE}, atas nama {PER}.",
        "Email saya {EMAIL}, nama {PER}.",
        "NIK saya {NIK}.",
        "Tolong hubungi {PHONE}.",
        "Kirim invoice ke {EMAIL}.",
        "Saya {PER}, NIK {NIK}, nomor HP {PHONE}.",
        "Verifikasi: {PER}, {NIK}, {PHONE}",
        "Hubungi saya di {PHONE} atau {EMAIL}.",
        "wa ke {PHONE} aja kak, a.n {PER}",
        "Email {EMAIL} tidak bisa login.",
        "Nomor {PHONE} ini milik {PER}.",
        "Ganti email akun saya jadi {EMAIL}.",
        "nik {NIK} a.n {PER} tlg dicek",
        "Nomor KTP {NIK}, alamat {ADDR}.",
        "Kode OTP tidak masuk ke {PHONE}.",
        "Saya {PER} ({EMAIL}), belum menerima tagihan.",
        "Telepon balik ke {PHONE} ya, cari {HON} {PER}.",
        "Email kantor {EMAIL}, alamat {ADDR}.",
    ],
    "negative": [
        "Saya mau jalan-jalan ke {CITY}, apakah paket roaming tersedia?",
        "Paket saya masih di jalan.",
        "Apakah ada gangguan di {CITY}?",
        "Bagaimana cara berhenti berlangganan?",
        "Berapa harga {PROD}?",
        "Promo {PROD} sampai kapan?",
        "Jalan tol ke {CITY} macet, sinyal hilang.",
        "Terima kasih, pelayanannya indah sekali.",
        "Saya mau kirim bunga untuk teman.",
        "Fajar tadi internet mati.",
        "Semoga rezeki lancar, terima kasih bantuannya.",
        "Sinyal di {CITY} bagus, tapi di rumah jelek.",
        "Saya sedang dalam perjalanan, nanti saya hubungi lagi.",
        "Jalan keluarnya bagaimana, modem sudah saya restart.",
        "Tagihan bulan {MONTH} naik jadi {AMOUNT}, kenapa?",
        "Kapan teknisi datang?",
        "Nomor tiket saya {TICKET}.",
        "Status tiket {TICKET} bagaimana?",
        "Nomor pelanggan {CUSTNO}, mohon dicek tagihannya.",
        "Apakah bisa bayar lewat {PAY}?",
        "Kenapa aplikasi {APP} tidak bisa dibuka?",
        "Mau upgrade dari {PROD} ke paket yang lebih cepat.",
        "Ada cabang di {CITY}?",
        "Saya pelanggan dari {CITY}.",
        "Jaringan 5G sudah ada di {CITY} belum?",
        "Kabel di jalan depan rumah putus.",
        "Kenapa jalan di depan rumah digali?",
        "Saya lagi di jalan, nanti lanjut chat ya.",
        "Tolong kirim ke alamat yang sama seperti sebelumnya.",
        "Berapa lama proses pindah alamat?",
        "Saya lupa password akun.",
        "OK terima kasih kak.",
        "Masih belum bisa, sudah saya coba berkali-kali.",
        "Apa itu {PROD}?",
        "Halo, selamat pagi.",
        "Kuota {DATA} habis dalam sehari, tolong cek.",
        "Indah banget pemandangannya, sayang sinyalnya jelek.",
        "Jaya terus {BRAND}!",
        "Paket {PRODNAME} cocok untuk keluarga?",
        "Bunga cicilannya berapa persen?",
        "Hari ini cerah, semoga internet juga lancar.",
        "Pak, kapan gangguannya selesai?",
        "Terima kasih Kak, sangat membantu.",
        "Bu, saya sudah bayar tadi pagi.",
        "Mas, modemnya bunyi terus.",
        "Kak, lampu LOS di modem merah.",
        "Bisa minta nomor telepon kantor pusat {BRAND}?",
        "Tagihan {MONTH} {YEAR} belum muncul di aplikasi {APP}.",
        "Kalau pindah ke {CITY}, nomor saya masih bisa dipakai?",
        "min kok lemot bgt sih dr td",
        "gmn cara cek sisa kuota?",
        "udh bayar via {PAY} tp status blm lunas",
        "Apakah ada teknisi yang standby di {CITY}?",
        "Perjalanan dari {CITY} ke {CITY} sinyalnya hilang terus.",
        "Mohon maaf, saya salah kirim pesan.",
        "Paket {PRODNAME} dan paket {PRODNAME} bedanya apa?",
        "Saya mau pesan paket {PRODNAME} untuk kantor.",
        "Pelangi setelah hujan, tapi internet tetap mati.",
        "Cahaya lampu modem berkedip-kedip.",
        "Rahmat Tuhan, akhirnya internet nyala lagi.",
        "Tolong jangan telepon saya di jam kerja.",
        "Nama paketnya apa ya yang paling murah?",
        "Alamat email support kalian apa?",
        "Alamatnya masih sama, tidak ada perubahan.",
        "Kirim ke rumah saja, alamatnya sudah terdaftar.",
        "Kenapa ada biaya tambahan {AMOUNT} di tagihan?",
        "Jam operasional CS di {CITY} sampai jam berapa?",
        "Saya mau refund, transaksi tanggal 12 {MONTH} gagal.",
        "Mohon dibantu ya kak, sudah dari {MONTH} begini terus.",
        "Nama saya sudah benar di aplikasi, tidak perlu diubah.",
        "Atas nama perusahaan, kami minta maaf atas keterlambatan pembayaran.",
    ],
}

DEV_TEMPLATES: dict[str, list[str]] = {
    "person": [
        "Permisi, saya {PER}, boleh minta bantuan?",
        "Nama akun saya {PER}, tapi saldo tidak bertambah.",
        "Dengan {PER}, ada yang bisa saya tanyakan soal tagihan?",
        "Pemilik nomor ini {HON} {PER}, saya anaknya.",
        "tlg bantu {HON} {PER} ya kak, beliau gaptek",
        "Kemarin sudah dibantu oleh {PER}, tapi masalahnya muncul lagi.",
        "Surat kuasa dari {PER} untuk {PER2} sudah saya siapkan.",
        "gw {PER}, mau stop langganan",
        "Petugas lapangan {PER} tidak bisa dihubungi.",
        "Saya {PER}, mahasiswa, ada paket khusus pelajar?",
        "Yang terdaftar sebagai pemilik: {PER}.",
    ],
    "address": [
        "Tolong jadwalkan ulang kunjungan ke {ADDR}.",
        "Saya mau pasang di rumah orang tua, {ADDR}.",
        "Gangguan juga dialami tetangga saya di {ADDR}.",
        "posisi sy skrg di {ADDR}",
        "Pindahkan titik pemasangan ke {ADDR} ya.",
        "Barang retur dikirim dari {ADDR}.",
        "Area {ADDR} kapan normal lagi?",
        "Alamat kantor cabang kami: {ADDR}",
        "Sudah dua minggu internet di {ADDR} tidak stabil.",
    ],
    "both": [
        "Saya {PER}, rumah saya di {ADDR}, tolong dibantu.",
        "Untuk {HON} {PER}, dikirim ke {ADDR}.",
        "{PER} yang tinggal di {ADDR} sudah bayar lunas.",
        "Mohon teknisi hubungi {HON} {PER} di {ADDR}.",
        "Nama saya {PER}. Saya kontrak di {ADDR} sejak {MONTH}.",
        "halo kak aku {PER}, alamat aku {ADDR}",
        "Konfirmasi: {PER}, {ADDR}, paket {PROD}.",
        "Pelanggan {PER} di {ADDR} melaporkan kabel putus.",
    ],
    "form": [
        "Nama Pelanggan : {PER}\nAlamat Pemasangan : {ADDR}\nKontak : {PHONE}",
        "Data diri\nNama: {PER}\nNIK: {NIK}\nDomisili: {ADDR}",
        "nama lengkap - {PER}\nalamat - {ADDR}",
    ],
    "regex": [
        "Silakan email ke {EMAIL} atas nama {PER}.",
        "HP aktif saya {PHONE}, NIK {NIK}.",
        "No. KTP {NIK} milik {HON} {PER}.",
        "Kontak darurat {PHONE}, alamat {ADDR}.",
    ],
    "negative": [
        "Kenapa sinyal hilang setiap hujan?",
        "Ada promo akhir tahun untuk {PROD}?",
        "Mohon info jadwal pemeliharaan jaringan di {CITY}.",
        "Kok jalan di komplek saya gelap, tiang lampunya kena kabel?",
        "Saya mau beli bunga papan lewat aplikasi, bisa pakai poin?",
        "Paket {PRODNAME} masih dijual?",
        "Bu, pesanan saya belum diproses.",
        "Jalan pintas untuk reset modem apa ya?",
        "Pelayanan di {CITY} ramah sekali, terima kasih.",
        "Kak, cara ganti password wifi bagaimana?",
        "Nomor tiket {TICKET} sudah ditutup padahal belum beres.",
        "Terima kasih banyak, semoga sukses selalu.",
    ],
}

HONORIFICS = [
    "Bapak", "Ibu", "Pak", "Bu", "Mas", "Mbak", "Kak", "Bang", "Sdr.", "Sdri.", "Tuan",
    "Nyonya", "Om", "Tante", "Teh", "Aa", "Dik", "Uda", "Uni", "Bli", "Mbok", "Koh", "Ci",
    "Dr.", "Prof.", "Hj.", "H.", "Ibu Hj.", "Bapak H.", "dr.",
]
BRANDS = ["NusaTel", "NusaNet", "NusaFiber", "Telkomsel", "IndiHome", "XL", "Indosat", "Smartfren", "Biznet", "MyRepublic"]
APPS = ["MyNusaTel", "NusaPay", "Shopee", "Tokopedia", "GoPay", "OVO", "DANA", "WhatsApp", "MyTelkomsel"]
PAYMENTS = ["BCA", "Mandiri", "BRI", "BNI", "Indomaret", "Alfamart", "GoPay", "OVO", "DANA", "QRIS", "virtual account", "kartu kredit"]
PRODUCTS = [
    "paket Unlimited 30GB", "paket 50 Mbps", "paket Keluarga", "NusaFiber 100", "kartu prabayar",
    "paket Combo 20GB", "paket internet bulanan", "paket 100 Mbps", "paket Streaming", "paket Gamer",
    "paket Pelajar", "paket Bisnis 200 Mbps", "paket roaming Asia", "paket nelpon",
]
# Product names that look like person names — strong hard negatives.
PRODUCT_NAMES = ["Surya", "Bintang", "Mentari", "Cahaya", "Pelangi", "Mutiara", "Permata", "Intan",
                 "Mawar", "Kencana", "Jaya", "Garuda", "Rajawali", "Merdeka", "Sakti", "Kilat"]
MONTHS = ["Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus",
          "September", "Oktober", "November", "Desember"]

GREETINGS = ["Halo, ", "Halo kak, ", "Pagi min, ", "Selamat siang, ", "min, ", "Assalamualaikum, ",
             "Permisi, ", "Kak, ", "Hai, ", "Selamat malam. ", "Maaf mengganggu, ", "Mohon bantuan, "]
CLOSINGS = [" Terima kasih.", " makasih kak", " Mohon dibantu ya.", " Terima kasih banyak 🙏",
            " thx", " 🙏", " Ditunggu kabarnya.", " Tolong segera ya.", " trims min"]

# informal rewrite map (only applied to template text, never to entity values)
INFORMAL = {
    "saya": ["sy", "aku", "gue"], "yang": ["yg"], "tidak": ["tdk", "gak", "ga", "nggak"],
    "sudah": ["udah", "udh", "sdh"], "belum": ["blm"], "tolong": ["tlg"], "dengan": ["dgn"],
    "untuk": ["utk", "buat"], "bisa": ["bs"], "nomor": ["no", "nmr"], "alamat": ["almt"],
    "kemarin": ["kmrn", "kemaren"], "sekarang": ["skrg"], "dari": ["dr"], "juga": ["jg"],
    "lagi": ["lg"], "kenapa": ["knp", "napa"], "bagaimana": ["gmn", "gimana"], "rumah": ["rmh"],
    "datang": ["dtg"], "kalau": ["kalo", "klo"], "karena": ["krn"], "saja": ["aja"],
    "tapi": ["tp"], "atas nama": ["an", "a.n."], "terima kasih": ["makasih", "trims"],
    "mohon": ["mhn"], "segera": ["sgr"], "banyak": ["byk"], "pesan": ["psn"],
}
